CREATE TABLE tasks(
    `id` INT NOT NULL AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    status BOOLEAN DEFAULT 0,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
);